POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNla3JldHVzZXIiLCJpZCI6IjYxMjFlMzMxYmExMTM5NTU3NGRiZjlmYyIsImlhdCI6MTYyOTYxMDgxMX0.I6r4Yy17iw59q8ZIhlVJ8Tk-YEeMeTFNIk7wcDAUrBU

{
   "likes": 17,
    "title": "Kommentoitava blogi",
    "author": "Pek ka",
    "url": "www.google.fi"

}