POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNla3JldHVzZXIiLCJpZCI6IjYxMDJmNmFlY2FhYjE0MzQ1NDcyY2VhOSIsImlhdCI6MTYyNzU4NjcyMH0.CUAqJ8QnNmGvY6yqYz2TwlVtR0WVYInNs68SgsuK1h8

{
   "likes": 17,

    "author": "Pekka",
    "url": "asfafsfasfsaas"

}